//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_Kard_Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Card
    {
        public int id { get; set; }
        public string number_card { get; set; }
        public System.DateTime finish_date { get; set; }
        public int owner_card { get; set; }
        public string cvv { get; set; }
    
        public virtual Owner_Card Owner_Card1 { get; set; }
    }
}
